### ISSUE TITLE
git config command from README fails

### ISSUE THREAD

**Issue by drielsma** [tarsius/ghub#21]
Hi!

I'm trying to follow the GHE instructions from the README but git complains that the key given is invalid.

```
~/src/emacs $ hub --version
git version 2.13.3
hub version 2.2.9
~/src/emacs $ git config eg_example_com.user employee
error: invalid key: eg_example_com.user
```

Thanks!

**Comment by tarsius** [comment]
It appears that I never actually tested this. :roll_eyes: 

Looks like we have no choice but to go with `ghub-username.gh.example.com.user`, which results in the noisy

```
[ghub-username "gh.example.com"]
	user = me
```

**Comment by tarsius** [comment]
I've fixed that now. `ghub` now uses `github.HOST.user`, e.g. `github.gh.example.com.user`.
