### ISSUE TITLE
Implement a user-ready authentication workflow

### ISSUE THREAD

**Issue by vermiculus** [tarsius/ghub#4]
The authentication workflow is something `gh.el` seems to do very, very well. I like the idea of using existing authentication configuration options, but it would be worthwhile creating an interactive workflow that will guide the user through this configuration when we run into #2.

Since it's not wrapping any resources, this seems to be in-scope for `ghub`.

**Comment by vermiculus** [comment]
On second thought, it would probably be in the better spirit of `ghub` (and `glab`) to only offer the authentication *options* as opposed to the actual workflow. At least, that's what I've implemented here.

A possible workflow implementation might be as follows:

```elisp
(defun ghub-authenticate (domain scopes note)
  "Authenticates on DOMAIN with SCOPES using NOTE."
  (unless (ghub--domain-configuration domain :secure)
    (user-error "Refusing to send password over unsafe connection; configure your token in `auth-sources'"))
  (let ((ghub-force-basic-authentication t)
        (ghub-domain domain)
        (user-real-login-name
         (ghub--domain-configuration domain :username)))
    (ghub-post "/authorizations" nil
               `((scopes . ,scopes)
                 (note . ,note)))))
```

…which reminds me, `ghub--domain-configuration` should probable be public…

**Comment by tarsius** [comment]
I have merged an alternative implementation. Could you please redo `ghub-authenticate` on top of that and open a new issue. Thanks!

**Comment by vermiculus** [comment]
Done 👍
